### PR TITLE
[jsk_uav_forest_simulation] add hector_quadrotor_gazebo in run_depend

### PR DESCRIPTION
**Pull request by knorth55**
`run_depend` `hector_quadrotor_gazebo` is missing.

### CODE REVIEW

**Comment by tongtybj** [comment]
Why needs this run_depend?

**Comment by knorth55** [comment]
The package is used in forest_simulation.launch.
https://github.com/tongtybj/jsk_uav_forest/blob/ac7435b129ec49f18365d3c8ee4720e547c87247/jsk_uav_forest_simulation/launch/forest_simulation.launch#L31

**Comment by tongtybj** [comment]
@knorth55  
Just a simple question.
So far, no problem without this PR.
So I wonder whether you meet some new problem or just want to specify this dependency explicitly.

**Comment by knorth55** [comment]
I tried to use this package in a lecture, and I clone this package.
At that time, I use `rosdep install` to install all the dependencies, but `hector_quadrotor_gazebo` was not installed, and `simulation.launch` could not find out the package.

**Comment by tongtybj** [comment]
@knorth55 

Did you read README.md, and follow the instruction like:
```
wstool merge -t src https://raw.githubusercontent.com/tongtybj/jsk_uav_forest/master/jsk_uav_forest.rosinstall
wstool update -t src
rosdep install -y -r --from-paths src --ignore-src --rosdistro $ROS_DISTRO
```

1. We explicitly add the git repositories about ```hector``` (including hector_quadcopter_gazeb )  in the ```jsk_uav_forest.rosinstall``` to compile from source, but not from debian package. 
2. I did in this way, because we only use the ```indigo_devel``` version of ``` hector ```, no matter what the ros distro of your PC (indigo, jade, kinetic, etc) is. So do not do ```rosdep install``` individually.
3. Beside ```hector``` related package, I also have lots of the dependency packages which are not written as  ```run_depend```, but are added in ```jsk_uav_forest.rosinstal```.

**Comment by knorth55** [comment]
if there is a deb release, i want to install deb package.
installation of packages from source with `.rosinstall` is what I want to avoid.
Actually, I can run the simulation with only deb packages, so I made this PR.

**Comment by tongtybj** [comment]
I definitely agree with your opinion, but the fact is if your pc is kinetic and do the same thing, it won`t work. 
I also try my best to install dependencies from deb, however there are two special cases to install from source.

1. want to use the specific branch version regardless of the ```ROS_DISTRO```.  For example, the kinectic version of ```hector``` is suck, so we consider to use the indigo version even in kinectic pc
2. add some additional function for the original repository(of course PR is sent, but not merged yet). Then we use the own forked repository in its instead. This  always happens for the hardware interfaces(DJI SDK).

**Comment by knorth55** [comment]
If the problem is `ROS_DISTRO`, how about making branches `indigo-devel` and `kinetic-devel`?

**Comment by tongtybj** [comment]
This is one of the solutions what I thought. 
However,  the ```hector``` dependencies is not the crucial part of this repository, and making different branches just for this is not efficiently, especially for the competition oriented repository.

**Comment by knorth55** [comment]
You are right, but I prefer branch solution.
Anyway, I just tried to use this package for lecture, so it doesn't matter.

**Comment by tongtybj** [comment]
Anyway, your advice is very important for the code management. Thx a lot!
We will take the branch solution into account.

**Pull request merged**
